version: "3.9"
services:
  mysql:
    image: mysql:8.0.31
    container_name: fsr
    ports:
      - 3306:3306
    volumes:
      - ./data:../fsr-data
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=JPA